language: rust
rust:
 - stable
 - beta
 - nightly
env:
  matrix:
    - FLAGS=""
    - FLAGS="--no-default-features"
script:
  - cargo build --verbose $FLAGS
  - cargo test --verbose $FLAGS
  - |
    [ $TRAVIS_RUST_VERSION != nightly ] || (
      cargo bench $FLAGS
    )
