language: rust
matrix:
  include:
    - rust: 1.12.0
    - rust: stable
    - rust: beta
    - rust: nightly
    - env: CROSS_TARGET=mips64-unknown-linux-gnuabi64
      rust: stable
      services: docker
      sudo: required
script: ci/script.sh
branches:
  only:
    - master
